## Read in datasets and count the tumor transgene markers
```{r transgene_read}
#| dependson: [scanbit_prep_mouse_gfp_rfp]
transgene_samples <-
    read_tsv(
        "misc/validation_geo_metadata.tsv",
        show_col_types = FALSE
    ) %>%
    filter(sample_group == "truthset validation") %>%
    pull(Sample_ID) %>%
    unique()

roberts_transgene_samples <-
    read_tsv(
        "misc/mouse_samples_Roberts_realign_metadata.tsv",
        show_col_types = FALSE
    ) %>%
    pull(Sample_ID)

ltbc_transgene_samples <- c("S0260", "S0261")

transgene_samples <- c(
    transgene_samples,
    roberts_transgene_samples,
    ltbc_transgene_samples
)

plot_point_size <- 0.5

sobj_list <- list()
for (this_sample in transgene_samples) {
    sobj_list[[this_sample]] <-
        qs::qread(paste0(
            "output/seurat_objects/individual/",
            this_sample,
            "_mouse.qs"
        )) %>%
        PercentageFeatureSet(pattern = "^tumor", col.name = "tumor_marker_pct")

    sobj_list[[this_sample]]$cell_group <- paste0(
        sobj_list[[this_sample]]$cluster_label,
        "_c",
        sobj_list[[this_sample]]$individ_clusters
    )

    for (this_cutoff in c(5, 10, 20, 30)) {
        sobj_list[[this_sample]] <- add_snv_group_to_sobj(
            sobj_list[[this_sample]],
            snv_group_file = paste0(
                "output/snv/transgene/snvs_",
                this_sample,
                "_",
                this_cutoff,
                "_groups.txt"
            ),
            new_columns = paste0(
                c("snv_group_", "snv_top_lvl_group_"),
                this_cutoff
            ),
            cell_group = "cell_group"
        )
    }

    tumor_markers <-
        grep(
            "^tumor",
            rownames(sobj_list[[this_sample]]),
            value = TRUE
        )

    if (length(tumor_markers) > 0) {
        sobj_list[[this_sample]]$tumor_marker_count <-
            FetchData(
                sobj_list[[this_sample]],
                vars = tumor_markers,
                layer = "counts"
            ) %>%
            rowSums()

        sobj_list[[this_sample]]$tumor_cell <-
            if_else(
                sobj_list[[this_sample]]$tumor_marker_count > 0,
                "Has transgene",
                "No transgene"
            )

        this_plot <-
            ((
                DimPlot(
                    sobj_list[[this_sample]],
                    group.by = c("cell_group"),
                    pt.size = plot_point_size,
                    label = TRUE,
                    label.box = TRUE,
                    repel = TRUE
                ) +
                    NoLegend() +
                    coord_fixed()
            ) +
                (
                    DimPlot(
                        sobj_list[[this_sample]],
                        group.by = c("tumor_cell"),
                        pt.size = plot_point_size,
                        label = TRUE,
                        label.box = TRUE,
                        repel = TRUE
                    ) +
                        NoLegend() +
                        coord_fixed()
                )) /
                ((
                    DimPlot(
                        sobj_list[[this_sample]],
                        group.by = c("snv_top_lvl_group_10"),
                        pt.size = plot_point_size,
                        label = TRUE,
                        label.box = TRUE,
                        repel = TRUE
                    ) +
                        NoLegend() +
                        coord_fixed()
                ) +
                    (
                        FeaturePlot(
                            sobj_list[[this_sample]],
                            features = "tumor_marker_count",
                            order = TRUE,
                            pt.size = plot_point_size
                        ) +
                            coord_fixed()
                    ))

        ggsave(
            paste0("output/figures/transgene/", this_sample, "_plots.pdf"),
            plot = this_plot,
            width = 15,
            height = 15
        )
    } else {
        sobj_list[[this_sample]] <- NULL
    }
}

merge(sobj_list[[1]], sobj_list[-1])@meta.data %>%
    as_tibble() %>%
    select(Sample_ID, tumor_cell, individ_clusters, cluster_label) %>%
    mutate(
        cell_group =
            paste0(
                cluster_label,
                "_c",
                individ_clusters
            )
    ) %>%
    select(-individ_clusters, cluster_label) %>%
    group_by(Sample_ID, cell_group, tumor_cell) %>%
    summarize(n = n(), .groups = "drop") %>%
    group_by(Sample_ID, cell_group) %>%
    mutate(proportion = n / sum(n)) %>%
    filter(tumor_cell == "Has transgene") %>%
    arrange(desc(proportion)) %>%
    write_tsv("output/snv_processing/transgene/transgene_tumor_clust.txt")


VlnPlot(sobj_list[["G0010"]], features = c("tumor_marker_pct", "tumor_marker_count"))
DimPlot(sobj_list[["G0016"]], group.by = "tumor_cell")
```

## Look at lineage tracing barcodes

```{r transgene_ltbc}
#| eval: FALSE
ltbc_samples <- c("S0260", "S0261")

marker_table <-
    parallel::mclapply(
        ltbc_samples,
        mc.cores = 2,
        function(this_sample) {
            sobj <-
                qs::qread(paste0(
                    "output/seurat_objects/individual/",
                    this_sample,
                    "_mouse.qs"
                ))

            ltbc_table <- gen_cellecta_bc_data(
                paste0(
                    "/home/gdrobertslab/lab/Counts_2/",
                    this_sample,
                    "/possorted_genome_bam.bam"
                ),
                samtools_module = "GCC/9.3.0 SAMtools/1.10", verbose = TRUE
            )

            ltbc_sub <-
                ltbc_table %>%
                mutate(
                    cid = paste0(cid, "-1"),
                    barcode = paste0(lt_14, "_", lt_30),
                    has_barcode = TRUE
                ) %>%
                select(-lt_14, -lt_30) %>%
                group_by(cid) %>%
                mutate(tumor_marker_count = n()) %>%
                slice_head(n = 1) %>%
                column_to_rownames("cid")

            sobj <-
                AddMetaData(
                    sobj,
                    ltbc_sub
                )

            # replace data missing from ltbc_table with values
            sobj$tumor_marker_count <-
                if_else(
                    is.na(sobj$tumor_marker_count),
                    0,
                    sobj$tumor_marker_count
                )

            sobj$has_barcode <-
                if_else(
                    is.na(sobj$has_barcode),
                    FALSE,
                    sobj$has_barcode
                )

            sobj$tumor_cell <-
                if_else(
                    sobj$tumor_marker_count > 0,
                    "Has transgene",
                    "No transgene"
                )

            marker_table <-
                sobj@meta.data %>%
                as_tibble() %>%
                select(
                    Sample_ID,
                    tumor_cell,
                    individ_clusters,
                    cluster_label
                ) %>%
                mutate(
                    cell_group =
                        paste0(
                            cluster_label,
                            "_c",
                            individ_clusters
                        )
                ) %>%
                select(-individ_clusters, cluster_label) %>%
                group_by(Sample_ID, cell_group, tumor_cell) %>%
                summarize(n = n(), .groups = "drop") %>%
                group_by(Sample_ID, cell_group) %>%
                mutate(proportion = n / sum(n)) %>%
                filter(tumor_cell == "Has transgene") %>%
                arrange(desc(proportion))

            return(marker_table)
        }
    ) %>%
    bind_rows()

write_tsv(
    marker_table,
    "output/snv_processing/transgene/transgene_tumor_clust_ltbc.txt"
)
```

```{r transgene_match}
snv_groups <-
    list.files(
        path = "output/snv/transgene",
        pattern = "10_groups.txt",
        full.names = TRUE
    ) %>%
    read_tsv(
        show_col_types = FALSE,
        id = "sample",
        col_names = c(
            "cell_group",
            "group",
            "top_lvl_group"
        )
    ) %>%
    mutate(
        Sample_ID = str_remove(sample, ".+/snvs_") %>%
            str_remove("_10_groups.txt")
    ) %>%
    select(-sample) %>%
    group_by(Sample_ID) %>%
    mutate(n_groups = length(unique(top_lvl_group))) %>%
    ungroup() %>%
    mutate(
        top_lvl_group = if_else(
            n_groups == 1,
            NA,
            top_lvl_group
        )
    )

min_transgene_prop <- 0.2

transgene_groups <-
    read_tsv(
        c(
            "output/snv_processing/transgene/transgene_tumor_clust.txt",
            "output/snv_processing/transgene/transgene_tumor_clust_ltbc.txt"
        ),
        show_col_types = FALSE
    ) # %>%
# filter(proportion > min_transgene_prop)

transgene_plot <-
    full_join(snv_groups, transgene_groups) %>%
    filter(Sample_ID != "S0123") %>% # this sample had no detected transgene
    mutate(
        top_lvl_group = if_else(
            is.na(top_lvl_group),
            "No SNV groups",
            if_else(
                top_lvl_group == "top_lvl_group0",
                "Tumor by SNV",
                "Non-tumor by SNV"
            )
        ),
        proportion = replace_na(proportion, 0)
    ) %>%
    ggplot(
        aes(
            color = top_lvl_group,
            x = proportion,
            y = Sample_ID
        )
    ) +
    ggbeeswarm::geom_beeswarm(cex = 1, size = 2) +
    labs(
        x = "Proportion of cells in cluster with transgene",
        y = "Samples",
        title = "Concordance Between SNV Tumor Identification and Truthset",
        color = NULL
    ) +
    theme(
        legend.position = "inside",
        legend.position.inside = c(0.88, 0.9)
    )

ggsave(
    "output/figures/transgene_beeswarm_plot.pdf",
    transgene_plot,
    width = 8,
    height = 6
)
```

