## Look at Counts for Our Reporter



### GSE247228

lentiviral green fluorescent protein (GFP) in tumor cells

```{r}
#cutoffs for feature hists
cutoff_tbl <- tribble(      ~sample,     ~feature, ~min_val, ~max_val,
                      "SRR26705626", "nCount_RNA",     1000,    40000,
                      "SRR26705626", "percent.mt",        0,       10, 
                      "SRR26705627", "nCount_RNA",     1000,    60000,
                      "SRR26705627", "percent.mt",        0,       10,
                      "SRR26705628", "nCount_RNA",     1000,    50000,
                      "SRR26705628", "percent.mt",        0,       10,
                      "SRR26705629", "nCount_RNA",     1000,    75000,
                      "SRR26705629", "percent.mt",        0,       10,
                      "SRR26705630", "nCount_RNA",     1000,    50000,
                      "SRR26705630", "percent.mt",        0,       10,
                      "SRR26705631", "nCount_RNA",     1000,    40000, 
                      "SRR26705631", "percent.mt",        0,       10) 

#read in data
sample_names <- grep("SRR", list.files("counts/GSE247228/"), value = TRUE)
obj_list <- lapply(sample_names, function(x) {
    sobj <- tenx_load_qc(paste0("counts/GSE247228/",
                                x,
                                "/outs/filtered_feature_bc_matrix"),
                         violin_plot = FALSE)
    sobj$eGFP_exp <- GetAssayData(sobj, layer = "counts")["eGFP", ]
    subset(sobj, features = rownames(sobj)[rownames(sobj) != "eGFP"])
    # sobj@assays$RNA$counts <- sobj@assays$RNA$counts[rownames(sobj) != "eGFP", ]
    return(sobj)
})
names(obj_list) <- sample_names

qc_plts <- lapply(sample_names, function(x) {
    cuts <- subset(cutoff_tbl, sample == x) %>%
        select(feature, min_val, max_val)
    ob <- obj_list[[x]]
    feature_hist(ob,
                 features = c("nCount_RNA", "percent.mt"),
                 cutoff_table = cuts) +
        ggtitle(x)
})

png("output/figures/GSE247228/qc_grid.png", height = 2000, width = 1600)
grid.arrange(grobs = qc_plts)
dev.off()

#qc and make egfp feature plots
obj_list <- lapply(sample_names, function(x) {
    ob <- obj_list[[x]]
    cuts <- subset(cutoff_tbl, sample == x) %>%
        column_to_rownames("feature")
    ob <- subset(ob,
                 nCount_RNA > cuts["nCount_RNA", "min_val"] &
                 nCount_RNA < cuts["nCount_RNA", "max_val"] &
                 percent.mt < cuts["percent.mt", "max_val"]) %>%
        process_seurat()
    ob$sample_id <- x
    png(paste0("output/figures/GSE247228/dimplot_egfp_", x, ".png"),
        width = 1000,
        height = 600)
    print(dimplot_better(ob, group = "seurat_clusters") |
    r_feature_plot(ob, features = "eGFP_exp"))
    dev.off()
    
    return(ob)
})

merged_obs <- merge(obj_list[[1]], obj_list[-1]) %>%
    process_seurat()
merged_obs <- JoinLayers(merged_obs)
#check for batch effects
dimplot_better(merged_obs, "sample_id")

#Going to binarize eGFP_exp
merged_obs$binarized_eGFP <- merged_obs$eGFP_exp > 0

dimplot_better(merged_obs, group  = "seurat_clusters")| r_feature_plot(merged_obs, features = "binarized_eGFP", pt.size = 0.3)
```

It seems like clusters 6, 9, and 11 are our eGFP expressing cells. I'm going to save this off as a seurat object as well as just a metadata file.

```{r write-off-GSE247228}
merged_ob$is_tumor <- merged_obs$seurat_clusters %in% c(6, 9, 11)

qs::qsave(merged_obs, "output/seurat_objects/merged_GSE247288.qs")
rownames_to_column(merged_obs@meta.data, "bc") %>%
    write.table(file = "output/metadata/metadata_GSE247288.tsv",
                sep = "\t",
                row.names = FALSE,
                quote = FALSE)

merged_ob <- qs::qread("output/seurat_objects/merged_GSE247288.qs")

r_dim_plot(merged_ob, group = "seurat_clusters") | r_feature_plot(merged_ob, features = "binarized_eGFP", order = FALSE)
```


### GSE201615

Cas9 in tumor cells, also dsRED

```{r gse201615}
ob_names <- list.files("counts/GSE201615") %>%
    grep(pattern = "output", invert = TRUE, value = TRUE)
obj_list <- list()
qc_plots <- list()
for (ob_name in ob_names) {
    ob <- 
        tenx_load_qc(paste0("counts/GSE201615/",
                            ob_name,
                            "/outs/filtered_feature_bc_matrix"),
                     violin_plot = FALSE)
    qc_plots[[ob_name]] <-
        feature_hist(ob,
                     c("nCount_RNA", "percent.mt"),
                     cutoff_table = tribble(~feature, ~min_val, ~max_val,
                                            "nCount_RNA", 1000,    30000,
                                            "percent.mt",    0,       10)) +
        ggtitle(label = ob_name)

    #remove RFP from counts matrix and add as metadata column
    ob$rfp_exp <- GetAssayData(ob, layer = "counts")["RFP", ]
    ob <- subset(ob, features = rownames(ob)[rownames(ob) != "RFP"])
    ob$sample_id <- ob_name

    obj_list[[ob_name]] <- subset(ob,
                                  nCount_RNA %in% c(1000:30000) &
                                  percent.mt < 10) %>%
        process_seurat()
    
}
#for each, 1000 < nCount_RNA < 30000, percent.mt < 10
grid.arrange(grobs = qc_plots)

grid.arrange(grobs = lapply(obj_list, r_feature_plot, "rfp_exp"))

#binarize rfp expression
for (ob in names(obj_list)) {
    obj_list[[ob]]$binarized_rfp <- obj_list[[ob]]$rfp_exp > 0
}

grid.arrange(grobs = lapply(obj_list, r_feature_plot, "binarized_rfp"), order = FALSE)

merged_obs <- merge(obj_list[[1]], obj_list[-1]) %>%
    process_seurat()

r_dim_plot(merged_obs) | r_feature_plot(merged_obs, c("binarized_rfp", "Col1a1"), order = FALSE)

prop.table(table(merged_obs$binarized_rfp, merged_obs$seurat_clusters), margin = 2) %>%
    round(3)
```

I'm convinced that cluster 6 here are our cancer cells

```{r}
merged_obs$is_tumor <- merged_obs$seurat_clusters == 6

qs::qsave(merged_obs, "output/seurat_objects/merged_GSE201615.qs")
```

### GSE215239

```{r}
samp_ids <- list.files("counts/GSE215239") %>%
    grep(pattern = "output", x = ., invert = TRUE, value = TRUE)
sample_list <- list()
for (ob in samp_ids) {
    tmp <-
        tenx_load_qc(
            paste0("counts/GSE215239/", ob, "/outs/filtered_feature_bc_matrix/"),
            violin_plot = FALSE
        )
    tmp$sample_id <- ob
    if ("FLUC" %in% rownames(tmp)) {
        tmp$fluc_present <- GetAssayData(tmp)["FLUC", ] > 0
        tmp <- subset(tmp, features = rownames(tmp[rownames(tmp) != "FLUC"]))
    } else {
        tmp$fluc_present <- 0
    }
    sample_list[[ob]] <- tmp
}

cuts <- tribble(~feature, ~min_val, ~max_val,
                "nCount_RNA", 1000, 25000,
                "percent.mt", 0, 15)
nCount <- lapply(sample_list, function(x) {
    feature_hist(
        x,
        features = c("nCount_RNA", "percent.mt"),
        cutoff_table = cuts
        ) +
        ggtitle(label = unique(x$sample_id))
})

grid.arrange(grobs = nCount)

sample_list <- lapply(sample_list, function(x) {
    subset(
        x,
        nCount_RNA > 1000 &
        nCount_RNA < 25000 &
        percent.mt < 15
    ) %>%
    process_seurat()
})

r_dim_plot(sample_list[[4]]) | r_feature_plot(sample_list[[4]], features = "FLUC")
```

I'm gonna merge this guy now

```{r}
merged_samps <- merge(sample_list[[1]], sample_list[-1]) %>%
    process_seurat() %>%
    JoinLayers()

r_feature_plot(merged_samps, features = "fluc_present") | r_dim_plot(merged_samps, group = "seurat_clusters")
r_dim_plot(merged_samps, group = c("sample_id", "seurat_clusters"), pt.size = 0.3, order = FALSE) + NoLegend()
table(merged_samps$fluc_present, merged_samps$sample_id)
```


### S0282

```{r}
fluc_gtf <- read.table("custom_ref/fluc/fluc.gtf", sep = "\t")
gene_ids <- sapply(strsplit(fluc_gtf$V9, ";"), `[`, 1) %>%
    str_remove("gene_id ") %>%
    unique()
gene_ids <- gene_ids[gene_ids %in% rownames(ob)]


ob <- tenx_load_qc("counts/S0282/S0282/outs/filtered_feature_bc_matrix",
                   violin_plot = FALSE)

feature_hist(ob, features = c("nCount_RNA", "percent.mt"))


ob <- subset(ob,
             nCount_RNA > 1000 &
             nCount_RNA < 12000 &
             percent.mt < 10) %>%
    process_seurat()

r_dim_plot(ob)


```