## Merge the mouse data by species and make DimPlots
```{r merge_dimplots_mouse}
#| dependson: read_raw_mouse
mouse_qs_files <-
    list.files(
        path = "output/seurat_objects/individual",
        pattern = "*_mouse.qs",
        full.names = TRUE
    )

sobj_list <-
    parallel::mclapply(
        mouse_qs_files,
        mc.cores = 5,
        mc.preschedule = FALSE,
        function(x) {
            qs::qread(x)
    })

merged_sobj_mouse <-
    merge(sobj_list[[1]], sobj_list[-1]) %>%
    JoinLayers() %>%
    process_seurat()

# I think we want the within_sample clusters since there is pretty severe batch effect
# opt_res <-
#     optimize_silhouette(merged_sobj_mouse, summary_plot = FALSE) %>%
#     arrange(desc(sil_vals)) %>%
#     pull(res_vals) %>%
#     head(1)

# merged_sobj_mouse <-
#     Seurat::FindClusters(merged_sobj_mouse, resolution = opt_res)

qs::qsave(merged_sobj_mouse, "output/seurat_objects/merged/merged_mouse.qs")

plot_name <-
    (DimPlot(
        merged_sobj_mouse,
        group.by = "cell_type",
        label = TRUE,
        label.box = TRUE,
        repel = TRUE,
        ncol = 1
    ) +
    NoLegend() +
    theme(aspect.ratio = 1)) +
    (DimPlot(
        merged_sobj_mouse,
        group.by = "Sample_ID",
        label = TRUE,
        label.box = TRUE,
        repel = TRUE,
        ncol = 1
    ) +
    NoLegend() +
    theme(aspect.ratio = 1))
ggsave(
    "output/figures/dimplot_mouse_cell_type_by_sample.pdf",
    plot_name,
    width = 15,
    height = 20
)
```

## Table of cell types for mouse data
```{r merge_mouse_cell_type_table}
#| dependson: merge_dimplots_mouse
merged_sobj_mouse <- qs::qread("output/seurat_objects/merged/merged_mouse.qs")

table(merged_sobj_mouse$cell_type, merged_sobj_mouse$Name) %>%
    as.data.frame() %>%
    pivot_wider(names_from = "Var2", values_from = "Freq") %>%
    DT::datatable()
```

## Merge the human data by species and make DimPlots
```{r merge_dimplots_human}
#| dependson: read_raw_human
sobj_qs_dir <- "output/seurat_objects/individual"

sobj_list <-
    lapply(
        samples_tsv$Sample_ID,
        function(x) {
            qs::qread(file.path(sobj_qs_dir, paste0(x, "_human.qs")))
    })

merged_sobj_human <-
    merge(sobj_list[[1]], sobj_list[-1]) %>%
    process_seurat() %>%
    JoinLayers()

qs::qsave(merged_sobj_human, "output/seurat_objects/merged/merged_human.qs")

plot_name <-
    DimPlot(
        merged_sobj_human,
        split.by = "Name",
        label = TRUE,
        repel = TRUE,
        ncol = 2
    ) +
    theme(aspect.ratio = 1)
ggsave(
    "output/figures/dimplot_human_by_description.pdf",
    plot_name,
    width = 10,
    height = 10
)
plot_name
```
