## Update Reference Genome

I need to add the fluorescent reporter sequence to our reference genome before aligning our fastqs. I'll be adding it to our 10x-mm10 reference genome.

First I'm going to make a copy of the mm10 gtf and fastq.

```{bash copy-fastq-gtf}
cp /home/gdrobertslab/lab/GenRef/10x-mm10/fasta/genome.fa custom_ref/mm10_genome.fa
cp /home/gdrobertslab/lab/GenRef/10x-mm10/genes/genes.gtf.gz custom_ref/mm10_genes.gtf.gz
chmod 744 custom_ref/
```

### eGFP

I will first need to create a file named GFP.fa containing the nucleotide sequence for our GFP protein.

```{bash make-new-ref}
#get number of bases in GFP.fa
grep -v "^>" custom_ref/eGFP/eGFP.fa | tr -d "\n" | wc
#720 bases

#lets make a custom gtf for gfp; \t helps us make new columns that are needed in the gtf; we need both the exon and transcript lines 
echo -e 'eGFP\tunknown\texon\t1\t720\t.\t+\t.\tgene_id "eGFP"; transcript_id "eGFP"; gene_biotype "protein_coding";\n'\
'eGFP\tunknown\ttranscript\t1\t720\t.\t+\t.\tgene_id "eGFP"; transcript_id "eGFP"; gene_biotype "protein_coding";\n'\
'eGFP\tunknown\tgene\t1\t720\t.\t+\t.\tgene_id "eGFP"; gene_name "eGFP"; gene_biotype "protein_coding";' > custom_ref/eGFP/eGFP.gtf

#copy mm10 reference FASTA over (so we can modify it and not screw up the og)

#append GFP.fa to end of mm10 genome
cp custom_ref/mm10_genome.fa custom_ref/eGFP/genome.fa
cat custom_ref/eGFP/eGFP.fa >> custom_ref/eGFP/genome.fa

#check that GFP "chromosome" is present
grep ">" custom_ref/eGFP/genome.fa

#copy over original gtf and gunzip
cp custom_ref/mm10_genes.gtf custom_ref/eGFP/genes.gtf.gz
gunzip custom_ref/eGFP/genes.gtf.gz

#append GFP gtf to mm10 gene file
cat custom_ref/eGFP/eGFP.gtf >> custom_ref/eGFP/genes.gtf

#Time to make our new reference using cellranger mkref
cellranger mkref --output-dir custom_ref/eGFP/demo_eGFP \
    --genome demo_eGFP \
    --fasta custom_ref/eGFP/genome.fa \
    --genes custom_ref/eGFP/genes.gtf
```

### RFP

also known as dsRed

I'm going to make a reference with just RFP and see if downsampled fastqs have any reads that map to it.

```{bash make-rfp-ref}
mkdir custom_ref/RFP
grep -v "^>" custom_ref/RFP/RFP.fa | tr -d "\n" | wc
#672 bases

echo -e 'RFP\tunknown\texon\t1\t672\t.\t+\t.\tgene_id "RFP"; transcript_id "RFP"; gene_biotype "protein_coding";\n'\
'RFP\tunknown\ttranscript\t1\t672\t.\t+\t.\tgene_id "RFP"; transcript_id "RFP"; gene_biotype "protein_coding";\n'\
'RFP\tunknown\tgene\t1\t672\t.\t+\t.\tgene_id "RFP"; gene_name "RFP"; gene_biotype "protein_coding";' > custom_ref/RFP/RFP.gtf

#copy over fasta and gtf files, and gunzip gtf
cp custom_ref/mm10_genome.fa custom_ref/RFP/genome.fa
cp custom_ref/mm10_genes.gtf.gz custom_ref/RFP/genes.gtf.gz
gunzip custom_ref/RFP/genes.gtf.gz

#give self write permission
chmod 774 custom_ref/RFP/*

#cat RFP gtf and fasta to mm10 files
cat custom_ref/RFP/RFP.fa >> custom_ref/RFP/genome.fa
cat custom_ref/RFP/RFP.gtf >> custom_ref/RFP/genes.gtf

#make just RFP reference
ml cellranger
cellranger mkref --output-dir custom_ref/RFP/full_RFP \
    --genome full_RFP \
    --fasta custom_ref/RFP/genome.fa \
    --genes custom_ref/RFP/genes.gtf \
    --jobmode=local
```

## Run cellranger count

### On eGFP data From GSE247228

```{bash mk-bams}
#run cellranger count!
sbatch cellranger_count_egfp.sh


```

### On GSE201615

```{bash GSE201615-cellranger-count}
sbatch cellranger_count_rfp.sh
```

### GSE215239

CT2A Gbm cells

```{bash GSE215239}
#manually made gtf and fasta containing fluc and gfp sequences, gonna make ref manually
species=mm10
ref_out=custom_ref/gfp_luc
plasmid=gfp_luc

cp custom_ref/${species}_genes.gtf.gz $ref_out/genes.gtf.gz
gunzip $ref_out/genes.gtf.gz

cp custom_ref/${species}_genome.fa $ref_out/genome.fa
chmod 774 $ref_out/*

cat $ref_out/$plasmid.fa >> $ref_out/genome.fa
cat $ref_out/$plasmid.gtf >> $ref_out/genes.gtf

ml cellranger
cellranger mkref \
    --output-dir $ref_out/ref_out \
    --genome $plasmid \
    --fasta $ref_out/genome.fa \
    --genes $ref_out/genes.gtf \
    --jobmode=local

bash helper_scripts/realign.sh \
    -f input/fastqs/GSE215239 \
    -o custom_ref/gfp_luc
```

### GSE189856

The plasmid provided in the paper didn't work, so I created a new one that contains the entire Cas9-GFP sequence as one gene, RFP, and Luc as well. These are located in gfp_rfp_luc

```{bash}
# bash helper_scripts/realign.sh \
#     -f input/fastqs/GSE189856 \
#     -g input/plasmid_files/pSpCas9-2A-GFP.gbk \
#     -s mm10 \
#     -p Cas9-GFP \
#     -o custom_ref/Cas9_GFP
cd custom_ref/gfp_rfp_luc
cp /home/gdrobertslab/lab/GenRef/10x-mm10/fasta/genome.fa .
cp /home/gdrobertslab/lab/GenRef/10x-mm10/genes/genes.gtf.gz .
gunzip genes.gtf.gz
chmod 774

# cat new genes to appropriate files
cat gfp_rfp_luc.fa >> genome.fa
cat gfp_rfp_luc.gtf >> genes.gtf

cellranger mkref --output-dir ref_out \
    --genome gfp_rfp_luc \
    --fasta genome.fa \
    --genes genes.gtf \
    --jobmode=local

cd ../..

fastqs=$(ls input/fastqs/GSE189856)
ml cellranger
sbatch --array 0-5 \
    --time 48:00:00 \
    helper_scripts/cellranger_count_template.sh \
    "$fastqs" \
    input/fastqs/GSE189856/ \
    counts/GSE189856 \
    custom_ref/gfp_rfp_luc/ref_out
```

### GSE158700

```{bash}
# have to construct reference first, since it's human and mouse cells
```

### On S0105

TurboRFP

```{bash}

```

### On S0282

fLuc sample. have to copy over fastqs from gdrobertslab

```{bash}
mkdir -p input/fastqs/S0282/S0282/
cp /home/gdrobertslab/lab/FASTQs_2/R0066/R0066/S0282* input/fastqs/S0282/S0282/.

# bash helper_scripts/realign.sh \
#     -f input/fastqs/S0282 \
#     -g input/plasmid_files/fluc.gbk \
#     -s mm10 \
#     -p fluc \
#     -o custom_ref/fluc
fastqs
ml cellranger
sbatch --array 0-0 \
    --time 48:00:00 \
    helper_scripts/cellranger_count_template.sh \
    "S0282" \
    input/fastqs/S0282/ \
    counts/S0282 \
    custom_ref/fluc/ref_out


    
```