Before I download all the available data, I'm going to test it on the control samples from GSE247228.

The sra Run numbers are as follows:
    - SRR26705626
    - SRR26705627
    - SRR26705629

## Get FASTQ Files

I'll be using SRA-Toolkit/2.10.8 for this. Specifically, the `fasterq-dump` function.

### GSE247228

```{bash get-computing-power}
srun_l -c 12 -p himem --x11 --pty bash
```

```{bash get-fastqs}
ml SRA-Toolkit/2.10.8
fasterq-dump --outdir input/fastqs/GSE247228 --progress SRR26705626 SRR26705627 SRR26705629 SRR26705628 SRR26705630 SRR26705631
```

### GSE179077

Fluorescent UnaG in hypoxic glioblastoma cells

```{bash get-unag-fastqs}
mkdir input/fastqs/GSE179077
fasterq-dump --outdir input/fastqs/GSE179077 --progress SRR29428580 SRR29428581 SRR29428582 SRR29428583 SRR29428584 SRR29428585 SRR29428586 SRR29428587
```

## Update Reference Genome

I need to add the fluorescent reporter sequence to our reference genome before aligning our fastqs. I'll be adding it to our 10x-mm10 reference genome.

### eGFP

I will first need to create a file named GFP.fa containing the nucleotide sequence for our GFP protein.

```{bash make-new-ref}
#get number of bases in GFP.fa
grep -v "^>" custom_ref/eGFP/eGFP.fa | tr -d "\n" | wc
#720 bases

#lets make a custom gtf for gfp; \t helps us make new columns that are needed in the gtf; we need both the exon and transcript lines 
echo -e 'eGFP\tunknown\texon\t1\t720\t.\t+\t.\tgene_id "eGFP"; transcript_id "eGFP"; gene_biotype "proetin_coding";\n'\
'eGFP\tunknown\ttranscript\t1\t720\t.\t+\t.\tgene_id "eGFP"; transcript_id "eGFP"; gene_biotype "proetin_coding";\n'\
'eGFP\tunknown\tgene\t1\t720\t.\t+\t.\tgene_id "eGFP"; gene_name "eGFP"; gene_biotype "proetin_coding";' > custom_ref/eGFP/eGFP.gtf

#copy mm10 reference FASTA over (so we can modify it and not screw up the og)
cp /home/gdrobertslab/lab/GenRef/10x-mm10/fasta/genome.fa custom_ref/eGFP/genome.fa
chmod 744 custom_ref/eGFP/*

#append GFP.fa to end of mm10 genome
cat custom_ref/eGFP/eGFP.fa >> custom_ref/eGFP/genome.fa

#check that GFP "chromosome" is present
grep ">" custom_ref/eGFP/genome.fa

#copy over original gtf and gunzip
cp /home/gdrobertslab/lab/GenRef/10x-mm10/genes/genes.gtf.gz custom_ref/eGFP/.
chmod 744 custom_ref/eGFP/*
gunzip custom_ref/eGFP/genes.gtf.gz

#append GFP gtf to mm10 gene file
cat custom_ref/eGFP/eGFP.gtf >> custom_ref/eGFP/genes.gtf

#Time to make our new reference using cellranger mkref
cellranger mkref --output-dir custom_ref/eGFP/demo_eGFP \
    --genome demo_eGFP \
    --fasta custom_ref/eGFP/genome.fa \
    --genes custom_ref/eGFP/genes.gtf
```

### HRE-UnaG

Now I'm going to make a genome containing the hypoxic reporter element plus unag.

```{bash make-unag-ref}
#making a folder within custom ref for this, otherwise it'll get too cluttered
mkdir custom_ref/unag/

grep -v "^>" custom_ref/unag/hre_unag.fa | tr -d "\n" | wc
#8646 bases


echo -e 'HRE-dUnaG\tunknown\texon\t1\t8646\t.\t+\t.\tgene_id "HRE-dUnaG"; transcript_id "HRE-dUnaG"; gene_biotype "proetin_coding";\n'\
'HRE-dUnaG\tunknown\ttranscript\t1\t8646\t.\t+\t.\tgene_id "HRE-dUnaG"; transcript_id "HRE-dUnaG"; gene_biotype "proetin_coding";\n'\
'HRE-dUnaG\tunknown\tgene\t1\t8646\t.\t+\t.\tgene_id "HRE-dUnaG"; gene_name "HRE-dUnaG"; gene_biotype "proetin_coding";' > custom_ref/unag/hre_unag.gtf

#Going to append the gtf and fasta to the mm10
cp /home/gdrobertslab/lab/GenRef/10x-mm10/genes/genes.gtf.gz custom_ref/unag/genes.gtf.gz

cp /home/gdrobertslab/lab/GenRef/10x-mm10/fasta/genome.fa custom_ref/unag/genome.fa

chmod 744 custom_ref/unag

gunzip custom_ref/unag/genes.gtf.gz

#cat gtf and fasta for hre-unag to mm10 reference files
cat custom_ref/unag/hre_unag.fa >> custom_ref/unag/genome.fa
cat custom_ref/unag/hre_unag.gtf >> custom_ref/unag/genes.gtf

#make reference
ml cellranger
cellranger mkref --output-dir custom_ref/unag/unag_ref \
    --genome unag_ref \
    --fasta custom_ref/unag/genome.fa \
    --genes custom_ref/unag/genes.gtf \
    --jobmode=local \
    --localcores=8
```

## Run cellranger count

### On eGFP data From GSE247228

```{bash mk-bams}
# We need to convert our fastq names to a cellranger compatible format

for sra in SRR26705626 SRR26705627 SRR26705628 SRR26705629 SRR26705630 SRR26705631
do
    mkdir input/fastqs/GSE247228/${sra}
    mv input/fastqs/GSE247228/${sra}_1.fastq \
        input/fastqs/GSE247228/${sra}/${sra}_S1_R1_001.fastq
    mv input/fastqs/GSE247228/${sra}_2.fastq \
        input/fastqs/GSE247228/${sra}/${sra}_S1_R2_001.fastq
done

#run cellranger count!
sbatch cellranger_count_egfp.sh
```

### On unag data from GSE179077

```{bash mk-bams-GSE179077}
#rename to cellranger compatible format
for sra in SRR29428580 SRR29428581 SRR29428582 SRR29428583 SRR29428584 SRR29428585 SRR29428586 SRR29428587
do
    mkdir input/fastqs/GSE179077/${sra}
    mv input/fastqs/GSE179077/${sra}_1.fastq \
        input/fastqs/GSE179077/${sra}/${sra}_S1_R1_001.fastq
    mv input/fastqs/GSE179077/${sra}_2.fastq \
        input/fastqs/GSE179077/${sra}/${sra}_S1_R2_001.fastq
done
```

## Look at Counts for Our Reporter

### GSE247228

```{r}
#cutoffs for feature hists
cutoff_tbl <- tribble(      ~sample,     ~feature, ~min_val, ~max_val,
                      "SRR26705626", "nCount_RNA",     1000,    40000,
                      "SRR26705626", "percent.mt",        0,       10, 
                      "SRR26705627", "nCount_RNA",     1000,    50000,
                      "SRR26705627", "percent.mt",        0,       10,
                      "SRR26705628", "nCount_RNA",     1000,    50000,
                      "SRR26705628", "percent.mt",        0,       10,
                      "SRR26705629", "nCount_RNA",     1000,    60000,
                      "SRR26705629", "percent.mt",        0,       10,
                      "SRR26705630", "nCount_RNA",     1000,    50000,
                      "SRR26705630", "percent.mt",        0,       10,
                      "SRR26705631", "nCount_RNA",     1000,    40000, 
                      "SRR26705631", "percent.mt",        0,       10) 

#read in data
sample_names <- grep("SRR", list.files("counts/GSE247228/"), value = TRUE)
obj_list <- lapply(sample_names, function(x) {
    sobj <- tenx_load_qc(paste0("counts/GSE247228/",
                                x,
                                "/outs/filtered_feature_bc_matrix"),
                         violin_plot = FALSE)
    sobj$eGFP_exp <- GetAssayData(sobj, layer = "counts")["eGFP", ]
    sobj@assays$RNA$counts <- sobj@assays$RNA$counts[rownames(sobj) != "eGFP", ]
    return(sobj)
})
names(obj_list) <- sample_names

qc_plts <- lapply(sample_names, function(x) {
    cuts <- subset(cutoff_tbl, sample == x) %>%
        select(feature, min_val, max_val)
    ob <- obj_list[[x]]
    feature_hist(ob,
                 features = c("nCount_RNA", "percent.mt"),
                 cutoff_table = cuts) +
        ggtitle(x)
})
grid.arrange(grobs = qc_plts)

#make egfp feature plots
egfp_by_clust <- lapply(sample_names, function(x) {
    ob <- obj_list[[x]]
    
})

```